services:
  mariadb:
    image: mariadb:10.11.2
    env_file:
      - ${XEBRO_ROOT_DIR}/.env
      - ${XEBRO_ROOT_DIR}/.env.local
    
    ports:
      - published: 3306
        target: 3306
    volumes:
      - ${XEBRO_ROOT_DIR}/docker/.tmp/mariadb/:/docker-entrypoint-initdb.d/:rw
networks:
  default:
    external: true
    name: ${XEBRO_PROJECT_NAME}
