services:
  mariadb:
    image: mariadb:10.11.2
    env_file:
      - ${XEBRO_ROOT_DIR}/.env
      - ${XEBRO_ROOT_DIR}/.env.local
    
    ports:
      - published: 3306
        target: 3306
    volumes:
      - ${XEBRO_ROOT_DIR}/var/mariadb/:/docker-entrypoint-initdb.d/:rw
#      - ${XEBRO_ROOT_DIR}/docker/mari odb/init/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql:ro
